// users
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// loan
export const GET_USER_LOAN_SUCCESS = 'GET_USER_LOAN_SUCCESS';
export const GET_ALL_LOAN_SUCCESS = 'GET_ALL_LOAN_SUCCESS';
export const APPROVE_DECLINE_SUCCESS = 'APPROVE_DECLINE_SUCCESS';
export const REPAY_LOAN_SUCCESS = 'REPAY_LOAN_SUCCESS';
